### ISSUE TITLE
Version 0.9.0 is broken with Gradle 4.5

### ISSUE THREAD

**Issue by aalmiray** [spring-gradle-plugins/spring-bintray-plugin#1]
Builds crashes with

    Caused by: java.lang.NoSuchMethodError: org.gradle.api.internal.tasks.DefaultTaskDependency.getValues()Ljava/util/Set;
            at io.spring.gradle.bintray.SpringBintrayPlugin$configureCreateVersionTask$1.execute(SpringBintrayPlugin.kt:134)
            at io.spring.gradle.bintray.SpringBintrayPlugin$configureCreateVersionTask$1.execute(SpringBintrayPlugin.kt:18)
            at org.gradle.internal.Actions$FilteredAction.execute(Actions.java:205)
            at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:136)
            at org.gradle.api.internal.tasks.RealizableTaskCollection.all(RealizableTaskCollection.java:192)
            at org.gradle.api.internal.DefaultDomainObjectCollection.withType(DefaultDomainObjectCollection.java:159)
            at io.spring.gradle.bintray.SpringBintrayPlugin.configureCreateVersionTask(SpringBintrayPlugin.kt:125)
            at io.spring.gradle.bintray.SpringBintrayPlugin.access$configureCreateVersionTask(SpringBintrayPlugin.kt:18)
            at io.spring.gradle.bintray.SpringBintrayPlugin$apply$1.execute(SpringBintrayPlugin.kt:54)
            at io.spring.gradle.bintray.SpringBintrayPlugin$apply$1.execute(SpringBintrayPlugin.kt:18)
            at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
            at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
            at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
            at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
            at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
            at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
            ... 91 more

------------------------------------------------------------
Gradle 4.5
------------------------------------------------------------

Build time:   2018-01-24 17:04:52 UTC
Revision:     77d0ec90636f43669dc794ca17ef80dd65457bec

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_162 (Oracle Corporation 25.162-b12)
OS:           Mac OS X 10.12.5 x86_64

**Comment by aalmiray** [comment]
Additional information from Cedric Champeau -> https://twitter.com/cedricchampeau/status/956541526867415046
